### ISSUE TITLE
[Fix] - 쿠키 에러 3차 핫픽스

### ISSUE THREAD

**Issue by sscoderati** [Team-Blitz-Steady/steady-client#207]
## 🚨 문제 상황
<img width="336" alt="스크린샷 2023-11-19 오전 11 53 51" src="https://github.com/Team-Blitz-Steady/steady-client/assets/69716992/d06b97ab-658b-4f6d-a52a-82fa1e60c18a">

로그아웃 수행 시 쿠키가 안 지워집니다...?

## 🛠️ 해결 과정
어차피 쿠키를 지우는 방법은 해당 쿠키의 유효 기간을 만료시키는 것이기 때문에, next에서 제공하는 `cookies().delete()`로 쿠키를 지우는 데 실패할 시 아래와 같은 응답을 반환하고자 합니다.
```js
return NextResponse.json(
    { message: "Logout failed! Delete Cookies Manually..." },
    {
      status: 200,
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-expect-error
      headers: {
        "content-type": "application/json",
        "Set-Cookie": [
          "access_token=; Path=/; Max-Age=0",
          "refresh_token=; Path=/; Max-Age=0",
        ],
      },
    },
  );
```

## 🚧 특이 사항
그런데 한가지 논의가 필요한 부분은 headers 윗줄에 `// @ts-expect-error` (런타임에서 오류가 없고 정말 단순 타입 에러인 경우 사용하는 주석)를 추가해도 되는건지... TS에 의하면 저 "Set-Cookie"는 string[]이 아닌 string만 받아야한다고 하는데, 일단 런타임 실행 결과를 봅시다.
<img width="671" alt="스크린샷 2023-11-19 오전 11 58 33" src="https://github.com/Team-Blitz-Steady/steady-client/assets/69716992/210a5e5f-8663-4768-9289-c2a3b01114f6">
위 사진과 같이 Set-Cookie 두 녀석이 잘 날아오는 것을 알 수 있죠?
그래서 팀원 분들 생각이 궁금합니다.
추가해도 되면 추가해서 두 쿠키를 전부 지울 예정이고
안되면 액세스 토큰만 지우거나, `clearAccess`, `clearRefresh`라는 Route Handler 두 녀석을 추가해서 해결 하려고 합니다..

**Comment by JIY00N2** [comment]
단순타입에러에 대한 처리라면 괜찮을 것 같습니다 ㅎㅎ
