### ISSUE TITLE
[Fix] - 공통 컴포넌트 Dropdown 페이지 이동 시 자동 닫힘 요청

### ISSUE THREAD

**Issue by JeongWuk** [Team-Blitz-Steady/steady-client#90]
## 🚨 문제 상황

- 공통 컴포넌트 Dropdown 페이지 이동 시 상태가 유지됩니다...!

## 🚧 특이 사항
이슈를 읽을 때 참고할 사항 작성

**Comment by sscoderati** [comment]
close with #104
